@startuml

class Piloto {
  -id : int
  -nome : string
  -idade : int
}

class Equipa {
  -nome : string
}

class Veiculo {
  -modelo : string
}

class Corrida {
  -nome : string
}

class Participação {
  -posição : int
  -tempo : float
}

' Relações
Equipa "1" -- "0..*" Piloto
Equipa "1" -- "0..*" Veiculo

Piloto "1" -- "0..*" Participação
Corrida "1" -- "0..*" Participação

Participação "0..*" --> "1" Piloto
Participação "0..*" --> "1" Corrida

@enduml