@startuml

title SSD: UC10 - Consultar Classificação

actor Utilizador
participant Sistema

Utilizador -> Sistema : pedirListaCorridas()
Sistema    --> Utilizador : listaCorridas

Utilizador -> Sistema : selecionarCorrida(idCorrida)
Sistema    -> Sistema  : obterParticipacoes(idCorrida)
Sistema    -> Sistema  : ordenarPorPosicao()

alt [corrida tem participações]
  Sistema --> Utilizador : classificacao
else [sem participações registadas]
  Sistema --> Utilizador : semResultados
end

@enduml
