@startuml
title SSD: UC9 - Associar Veículo a Equipa

actor Utilizador
participant ":Controller" as C
participant ":VeiculoView" as V
participant ":VeiculoService" as S
participant ":EquipaContainer" as EC
participant ":VeiculoContainer" as VC

Utilizador -> C : seleciona "Veículos > Associar a equipa"
C -> V : getId()
V --> C : veiculoId
C -> V : getEquipaId()
V --> C : equipaId
C -> S : assignEquipa(veiculoId, equipaId)
S -> EC : get(equipaId)

alt equipa não existe
  EC --> S : throws NoDataException
  S --> C : throws NoDataException
  C -> V : printError(msg)
else sucesso
  S -> VC : assignEquipa(veiculoId, equipaId)
  S -> S : repo.persist()
  S --> C : ok
  C -> V : printMessage("Veiculo associado a equipa.")
end
@enduml
